"""empty message

Revision ID: 61bb3cff13dc
Revises: dfbce9bb2d3f
Create Date: 2016-12-22 18:08:38.493487

"""

# revision identifiers, used by Alembic.
revision = '61bb3cff13dc'
down_revision = 'dfbce9bb2d3f'

import sqlalchemy as sa
from alembic import op


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fund_contract_sum', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fund_income_sum', sa.Integer(), nullable=True))
        batch_op.drop_column('income_sum')
        batch_op.drop_column('contract_sum')

    with op.batch_alter_table('techfees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fee_income', sa.Integer(), nullable=True))
        batch_op.drop_column('income_fee')

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('techfees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('income_fee', sa.INTEGER(), nullable=True))
        batch_op.drop_column('fee_income')

    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contract_sum', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('income_sum', sa.INTEGER(), nullable=True))
        batch_op.drop_column('fund_income_sum')
        batch_op.drop_column('fund_contract_sum')

    ### end Alembic commands ###
