"""empty message

Revision ID: dfbce9bb2d3f
Revises: e749b131469b
Create Date: 2016-12-21 14:14:31.435611

"""

# revision identifiers, used by Alembic.
revision = 'dfbce9bb2d3f'
down_revision = 'e749b131469b'

import sqlalchemy as sa
from alembic import op


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('techfees') as batch_op:
        batch_op.drop_column('contract_sum')

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('techfees', sa.Column('contract_sum', sa.INTEGER(), nullable=True))
    ### end Alembic commands ###
