"""empty message

Revision ID: e749b131469b
Revises: 1b61dc0c97a6
Create Date: 2016-12-19 18:14:23.276155

"""

# revision identifiers, used by Alembic.
revision = 'e749b131469b'
down_revision = '1b61dc0c97a6'

import sqlalchemy as sa
from alembic import op


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('bonus_sum', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'bonus_sum')
    ### end Alembic commands ###
